
[theme]
base="dark"
textColor="#00d4aa"

[theme]
base = "light"
primaryColor = "#2e86de"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"



